from edps import task, SCIENCE
from .metis_datasources import *

# --- Processing tasks ---


lingain_ifu_task = (task("metis_ifu_lingain")
                .with_recipe("metis_det_lingain")
                .with_main_input(detlin_ifu_raw)
                .with_associated_input(bad_pix_ifu_calib, min_ret=0)
                .build())

dark_ifu_task = (task("metis_ifu_dark")
             .with_recipe("metis_det_dark")
             .with_main_input(dark_ifu_raw)
             .with_associated_input(bad_pix_ifu_calib, min_ret=0)
             .with_associated_input(lingain_ifu_task)
             .with_associated_input(calib_persistence, min_ret=0)
             .with_input_filter(linearity_det_ifu_class, gain_map_ifu_class, persistence_class)
             .build())

distortion_ifu_task = (task("metis_ifu_distortion")
                   .with_recipe("metis_ifu_distortion")
                   .with_main_input(distortion_ifu_raw)
                   .with_associated_input(bad_pix_ifu_calib, min_ret=0)
                   .with_associated_input(lingain_ifu_task)
                   .with_associated_input(calib_persistence, min_ret=0)
                   .with_associated_input(calib_pinhole)
                   .with_associated_input(dark_ifu_task)
                   .with_input_filter(linearity_det_ifu_class, gain_map_ifu_class, master_dark_ifu_class, persistence_class, pinhole_table_class)
                   .build())

wave_ifu_task = (task("metis_ifu_wavecal")
             .with_recipe("metis_ifu_wavecal")
             .with_main_input(wave_ifu_raw)
             .with_associated_input(bad_pix_ifu_calib, min_ret=0)
             .with_associated_input(lingain_ifu_task)
             .with_associated_input(calib_persistence, min_ret=0)
             .with_associated_input(dark_ifu_task)
             .with_associated_input(distortion_ifu_task)
             .with_input_filter(linearity_det_ifu_class, gain_map_ifu_class, master_dark_ifu_class, distortion_table_ifu_class, persistence_class, pinhole_table_class)
             .build())

rsrf_ifu_task = (task("metis_ifu_rsrf")
             .with_recipe("metis_ifu_rsrf")
             .with_main_input(rsrf_ifu_raw)
             .with_associated_input(bad_pix_ifu_calib, min_ret=0)
             .with_associated_input(lingain_ifu_task)
             .with_associated_input(calib_persistence, min_ret=0)
             .with_associated_input(dark_ifu_task)
             .with_associated_input(distortion_ifu_task)
             .with_associated_input(wcu_off_ifu_raw)
             .with_associated_input(wave_ifu_task)
             .with_input_filter(linearity_det_ifu_class, gain_map_ifu_class, master_dark_ifu_class, distortion_table_ifu_class, wave_cal_ifu_class, persistence_class)
             .build())

std_ifu_task = (task("metis_ifu_std_reduce")
            .with_recipe("metis_ifu_reduce")
            .with_main_input(std_ifu_raw)
            .with_associated_input(bad_pix_ifu_calib, min_ret=0)
            .with_associated_input(lingain_ifu_task)
            .with_associated_input(calib_persistence, min_ret=0)
            .with_associated_input(dark_ifu_task)
            .with_associated_input(distortion_ifu_task)
            .with_associated_input(wave_ifu_task)
            .with_associated_input(rsrf_ifu_task)
            .with_associated_input(sky_ifu_raw)
            .with_input_filter(linearity_det_ifu_class, gain_map_ifu_class, master_dark_ifu_class, persistence_class, distortion_table_ifu_class, wave_cal_ifu_class, rsrf_prod_ifu_class)
            .build())

sci_ifu_task = (task("metis_ifu_sci_reduce")
            .with_recipe("metis_ifu_reduce")
            .with_main_input(sci_ifu_raw)
            .with_associated_input(bad_pix_ifu_calib, min_ret=0)
            .with_associated_input(lingain_ifu_task)
            .with_associated_input(calib_persistence, min_ret=0)
            .with_associated_input(dark_ifu_task)
            .with_associated_input(distortion_ifu_task)
            .with_associated_input(wave_ifu_task)
            .with_associated_input(rsrf_ifu_task)
            .with_associated_input(sky_ifu_raw)
            .with_input_filter(linearity_det_ifu_class, gain_map_ifu_class, master_dark_ifu_class, persistence_class, distortion_table_ifu_class, wave_cal_ifu_class, rsrf_prod_ifu_class)
            .build())

telluric_sci_ifu_task = (task("metis_ifu_sci_telluric")
                .with_recipe("metis_ifu_telluric")
                .with_main_input(sci_ifu_task)
                .with_associated_input(calib_flux_std)
                .with_associated_input(calib_lsf_kernel)
                .with_associated_input(calib_atm_profile)
                .with_input_filter(sci_reduce_ifu_class, sci_comb_ifu_class, fluxstd_ifu_class, lsf_kernel_class, atm_profile_class)
                .with_output_filter(telluric_ifu_class)
                .build())

telluric_std_ifu_task = (task("metis_ifu_std_telluric")
                 .with_recipe("metis_ifu_telluric")
                 .with_main_input(std_ifu_task)
                 .with_associated_input(calib_flux_std)
                 .with_associated_input(calib_lsf_kernel)
                 .with_associated_input(calib_atm_profile)
                 .with_input_filter(std_comb_ifu_class, fluxstd_ifu_class, lsf_kernel_class, atm_profile_class)
                 .with_output_filter(flux_tab_class)
                 .build())

calibrate_ifu_task = (task("metis_ifu_calibrate")
                  .with_recipe("metis_ifu_calibrate")
                  .with_main_input(sci_ifu_task)
                  .with_associated_input(telluric_sci_ifu_task)
                  .with_associated_input(telluric_std_ifu_task)
                  .with_input_filter(sci_reduce_ifu_class, flux_tab_class, telluric_ifu_class)
                  .build())

post_process_ifu_task = (task("metis_ifu_postprocess")
                     .with_recipe("metis_ifu_postprocess")
                     .with_main_input(calibrate_ifu_task)
                     .with_meta_targets([SCIENCE])
                     .build())
