from edps import task, SCIENCE
from .metis_datasources import *

# --- Processing tasks ---


ifu_lingain_task = (task("metis_ifu_lingain")
                .with_recipe("metis_det_lingain")
                .with_main_input(detlin_ifu_raw)
                .with_associated_input(badpix_map_ifu, min_ret=0)
                .with_associated_input(ifu_wcu_off_raw)
                .build())

ifu_dark_task = (task("metis_ifu_dark")
             .with_recipe("metis_det_dark")
             .with_main_input(dark_ifu_raw)
             .with_associated_input(badpix_map_ifu, min_ret=0)
             .with_associated_input(ifu_lingain_task)
             .with_associated_input(persistence_map, min_ret=0)
             .with_input_filter(linearity_ifu_class, gain_map_ifu_class, persistence_map_class)
             .build())

ifu_distortion_task = (task("metis_ifu_distortion")
                   .with_recipe("metis_ifu_distortion")
                   .with_main_input(ifu_distortion_raw)
                   .with_associated_input(badpix_map_ifu, min_ret=0)
                   .with_associated_input(ifu_lingain_task)
                   .with_associated_input(persistence_map, min_ret=0)
                   .with_associated_input(pinhole_table)
                   .with_associated_input(ifu_dark_task)
                   .with_input_filter(linearity_ifu_class, gain_map_ifu_class, master_dark_ifu_class, persistence_map_class, pinhole_table_class)
                   .build())

ifu_wavecal_task = (task("metis_ifu_wavecal")
             .with_recipe("metis_ifu_wavecal")
             .with_main_input(ifu_wave_raw)
             .with_associated_input(badpix_map_ifu, min_ret=0)
             .with_associated_input(ifu_lingain_task)
             .with_associated_input(persistence_map, min_ret=0)
             .with_associated_input(ifu_dark_task)
             .with_associated_input(ifu_distortion_task)
             .with_input_filter(linearity_ifu_class, gain_map_ifu_class, master_dark_ifu_class, ifu_distortion_table_class, persistence_map_class, pinhole_table_class)
             .build())

ifu_rsrf_task = (task("metis_ifu_rsrf")
             .with_recipe("metis_ifu_rsrf")
             .with_main_input(ifu_rsrf_raw)
             .with_associated_input(badpix_map_ifu, min_ret=0)
             .with_associated_input(ifu_lingain_task)
             .with_associated_input(persistence_map, min_ret=0)
             .with_associated_input(ifu_dark_task)
             .with_associated_input(ifu_distortion_task)
             .with_associated_input(ifu_wcu_off_raw)
             .with_associated_input(ifu_wavecal_task)
             .with_input_filter(linearity_ifu_class, gain_map_ifu_class, master_dark_ifu_class, ifu_distortion_table_class, ifu_wavecal_class, persistence_map_class)
             .build())

ifu_std_reduce_task = (task("metis_ifu_std_reduce")
            .with_recipe("metis_ifu_reduce")
            .with_main_input(ifu_std_raw)
            .with_associated_input(badpix_map_ifu, min_ret=0)
            .with_associated_input(ifu_lingain_task)
            .with_associated_input(persistence_map, min_ret=0)
            .with_associated_input(ifu_dark_task)
            .with_associated_input(ifu_distortion_task)
            .with_associated_input(ifu_wavecal_task)
            .with_associated_input(ifu_rsrf_task)
            .with_associated_input(ifu_sky_raw)
            .with_input_filter(linearity_ifu_class, gain_map_ifu_class, master_dark_ifu_class, persistence_map_class, ifu_distortion_table_class, ifu_wavecal_class, ifu_rsrf_class)
            .build())

ifu_sci_reduce_task = (task("metis_ifu_sci_reduce")
            .with_recipe("metis_ifu_reduce")
            .with_main_input(ifu_sci_raw)
            .with_associated_input(badpix_map_ifu, min_ret=0)
            .with_associated_input(ifu_lingain_task)
            .with_associated_input(persistence_map, min_ret=0)
            .with_associated_input(ifu_dark_task)
            .with_associated_input(ifu_distortion_task)
            .with_associated_input(ifu_wavecal_task)
            .with_associated_input(ifu_rsrf_task)
            .with_associated_input(ifu_sky_raw)
            .with_input_filter(linearity_ifu_class, gain_map_ifu_class, master_dark_ifu_class, persistence_map_class, ifu_distortion_table_class, ifu_wavecal_class, ifu_rsrf_class)
            .build())

ifu_sci_telluric_task = (task("metis_ifu_sci_telluric")
                .with_recipe("metis_ifu_telluric")
                .with_main_input(ifu_sci_reduce_task)
                .with_associated_input(fluxstd_catalog)
                .with_associated_input(lsf_kernel)
                .with_associated_input(atm_profile)
                .with_input_filter(ifu_sci_reduced_class, ifu_sci_combined_class, fluxstd_catalog_class, lsf_kernel_class, atm_profile_class)
                .with_output_filter(ifu_telluric_class)
                .build())

ifu_std_telluric_task = (task("metis_ifu_std_telluric")
                 .with_recipe("metis_ifu_telluric")
                 .with_main_input(ifu_std_reduce_task)
                 .with_associated_input(fluxstd_catalog)
                 .with_associated_input(lsf_kernel)
                 .with_associated_input(atm_profile)
                 .with_input_filter(ifu_std_combined_class, fluxstd_catalog_class, lsf_kernel_class, atm_profile_class)
                 .with_output_filter(flux_tab_class)
                 .build())

ifu_calibrate_task = (task("metis_ifu_calibrate")
                  .with_recipe("metis_ifu_calibrate")
                  .with_main_input(ifu_sci_reduce_task)
                  .with_associated_input(ifu_sci_telluric_task)
                  .with_associated_input(ifu_std_telluric_task)
                  .with_input_filter(ifu_sci_reduced_class, flux_tab_class, ifu_telluric_class)
                  .build())

ifu_postprocess_task = (task("metis_ifu_postprocess")
                     .with_recipe("metis_ifu_postprocess")
                     .with_main_input(ifu_calibrate_task)
                     .with_meta_targets([SCIENCE])
                     .build())