from edps import SCIENCE, QC1_CALIB, QC0, CALCHECKER
from edps import task, subworkflow, qc1calib, match_rules, FilterMode, calchecker
from .metis_datasources import *
from . import metis_keywords as metis_kwd

lm_img_lingain_task1 = (task('metis_lm_img_lingain1')
                .with_recipe("metis_det_lingain")
                .with_main_input(detlin_2rg_raw)
                .with_associated_input(lm_wcu_off_raw)
                .build())

lm_img_dark_task1 = (task('metis_lm_img_dark1')
            .with_main_input(dark_2rg_raw)
            .with_associated_input(lm_img_lingain_task1)
             .with_associated_input(persistence_map)
            .with_recipe("metis_det_dark")
            .build())

lm_img_flat_task1 = (task("metis_lm_img_flat1")
             .with_main_input(lm_flat_lamp_raw)
             .with_associated_input(lm_img_dark_task1)
             .with_associated_input(lm_img_lingain_task1)
             .with_associated_input(persistence_map)
             .with_recipe("metis_lm_img_flat")
             .build())

lm_img_distortion_task1 = (task('metis_lm_img_cal_distortion1')
                   .with_main_input(lm_distortion_raw)
                   .with_associated_input(lm_wcu_off_raw)
                   .with_associated_input(pinhole_table)
                   .with_associated_input(lm_img_lingain_task1)
                   .with_associated_input(persistence_map)
                   .with_recipe('metis_lm_img_distortion')
                   .build())

lm_img_basic_reduce_sci_task1 = (task('metis_lm_img_basic_reduce_sci1')
                    .with_recipe('metis_lm_img_basic_reduce')
                    .with_main_input(lm_image_sci_raw)
                    .with_associated_input(lm_img_lingain_task1)
                    .with_associated_input(lm_img_dark_task1)
                    .with_associated_input(lm_img_flat_task1)
                    .with_associated_input(persistence_map)
                    .with_meta_targets([SCIENCE])
                    .build())

lm_img_basic_reduce_sky_task1 = (task('metis_lm_img_basic_reduce_sky1')
                    .with_recipe('metis_lm_img_basic_reduce')
                    .with_main_input(lm_image_sky_raw)
                    .with_associated_input(lm_img_lingain_task1)
                    .with_associated_input(lm_img_dark_task1)
                    .with_associated_input(lm_img_flat_task1)
                    .with_associated_input(persistence_map)
                    .with_meta_targets([SCIENCE])
                    .build())

lm_img_basic_reduce_std_task1 = (task('metis_lm_img_basic_reduce_std1')
                    .with_recipe('metis_lm_img_basic_reduce')
                    .with_main_input(lm_image_std_raw)
                    .with_associated_input(lm_img_lingain_task1)
                    .with_associated_input(lm_img_dark_task1)
                    .with_associated_input(lm_img_flat_task1)
                    .with_associated_input(persistence_map)
                    .with_meta_targets([SCIENCE])
                    .build())

lm_img_background_sci_task1 = (task('metis_lm_img_background_sci1')
                    .with_recipe('metis_lm_img_background')
                    .with_main_input(lm_img_basic_reduce_sci_task1)
                    .with_associated_input(lm_img_basic_reduce_sky_task1)
                    .with_meta_targets([SCIENCE])
                    .build())

lm_img_basic_reduce_std_task1 = (task('metis_lm_img_background_std1')
                    .with_recipe('metis_lm_img_background')
                    .with_main_input(lm_img_basic_reduce_std_task1)
                    .with_associated_input(lm_img_basic_reduce_sky_task1)
                    .with_meta_targets([SCIENCE])
                    .build())

lm_img_standard_flux_task1 = (task('metis_lm_img_standard_flux1')
                    .with_recipe('metis_lm_img_std_process')
                    .with_main_input(lm_img_basic_reduce_std_task1)
                    .with_associated_input(fluxstd_catalog)
                    .with_meta_targets([SCIENCE])
                    .build())

lm_img_calib_task1 = (task('metis_lm_img_calib1')
             .with_recipe('metis_lm_img_calibrate')
             .with_main_input(lm_img_background_sci_task1)
             .with_associated_input(lm_img_standard_flux_task1)
             .with_associated_input(lm_img_distortion_task1)
             .with_meta_targets([SCIENCE])
             .build())
             
lm_ravc_post_task1 = (task('lm_ravc_post1')
             .with_recipe('metis_img_adi_cgrph')
             .with_main_input(lm_img_calib_task1)
             .with_meta_targets([SCIENCE])
             .build())
# QC1
