# HEADER KEYWORDS USED FOR CLASSIFICATION, GROUPING, AND ASSOCIATION.
instrume = "instrume"
pro_catg = "pro.catg"
dpr_type = "dpr.type"
dpr_catg = "dpr.catg"
drp_tech = "dpr.tech"
tpl_nexp = "tpl.nexp"
obs_id = "obs.id"
tpl_start = "tpl.start"
det_binx = "det.binx"
det_biny = "det.biny"
ins_mode = "ins.mode"
unique = "arcfile"
mjd_obs = "mjd-obs"
telescop = "telescop"
ocs_enabled_fe = "ocs.enabled.fe"
ins5_modsel_id = "ins5.modsel.id"
