#!/bin/bash
# =============================================================================
# METIS Pipeline - Run Test Suite
# =============================================================================
# Runs the pytest test suite against the SOF files generated by the EDPS
# workflows. Excludes tests marked as 'external', 'edps', or 'pyesorex'
# (these require full pipeline execution or external data).
#
# Usage (from inside WSL):
#   bash 04_run_tests.sh [--data-dir /path/to/data/output]
#
# Arguments:
#   --data-dir  Path to the extracted simulated data (containing imgLM/, imgN/, etc.)
#               Default: /mnt/d/simData_202602/output
#
# Prerequisites:
#   - 01_setup_wsl.sh has been run (or equivalent manual setup)
#   - 02_run_edps_workflows.sh has been run
#   - 03_create_sof_files.sh has been run
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration - EDIT THESE PATHS for your environment
# ---------------------------------------------------------------------------
REPO_PATH="/mnt/d/Repos/METIS_Pipeline"
VENV_PATH="/home/metis_env"
DATA_BASE="/mnt/d/simData_202602/output"

# ---------------------------------------------------------------------------
# Parse command-line arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --data-dir)
            DATA_BASE="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1"
            echo "Usage: $0 [--data-dir /path/to/data/output]"
            exit 1
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Setup environment
# ---------------------------------------------------------------------------
source "${VENV_PATH}/bin/activate"

export PYESOREX_PLUGIN_DIR="${REPO_PATH}/metisp/pymetis/src/pymetis/recipes"
export PYCPL_RECIPE_DIR="${REPO_PATH}/metisp/pyrecipes/"
export PYTHONPATH="${REPO_PATH}/metisp/pymetis/src/"
export SOF_DIR="/tmp/sof_for_tests"
export SOF_DATA="${DATA_BASE}/imgLM"

# ---------------------------------------------------------------------------
# Verify prerequisites
# ---------------------------------------------------------------------------
echo "=== METIS Pipeline Test Runner ==="
echo ""
echo "Configuration:"
echo "  REPO_PATH:            ${REPO_PATH}"
echo "  VENV_PATH:            ${VENV_PATH}"
echo "  SOF_DIR:              ${SOF_DIR}"
echo "  SOF_DATA:             ${SOF_DATA}"
echo "  PYESOREX_PLUGIN_DIR:  ${PYESOREX_PLUGIN_DIR}"
echo "  PYCPL_RECIPE_DIR:     ${PYCPL_RECIPE_DIR}"
echo "  PYTHONPATH:            ${PYTHONPATH}"
echo ""

if [ ! -d "${SOF_DIR}" ]; then
    echo "ERROR: SOF directory not found: ${SOF_DIR}"
    echo "Run 03_create_sof_files.sh first."
    exit 1
fi

SOF_COUNT=$(ls ${SOF_DIR}/*.sof 2>/dev/null | wc -l)
echo "SOF files available: ${SOF_COUNT}"
echo ""

# ---------------------------------------------------------------------------
# Run tests
# ---------------------------------------------------------------------------
echo "=== Running tests ==="
echo "  Excluding markers: external, edps, pyesorex"
echo ""

cd "${REPO_PATH}/metisp/pymetis"

python -m pytest src/pymetis/tests/ \
    -v \
    --tb=short \
    -m "not external and not edps and not pyesorex" \
    2>&1

echo ""
echo "=== Tests complete ==="
