name: Initialise workspace

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          sudo ./toolbox/install_dependencies_ubuntu.sh
          # python3 -m venv metispipe
          # . metispipe/bin/activate
          export PYCPL_RECIPE_DIR="$(pwd)/metisp/pyrecipes/"
          ./toolbox/install_edps.sh
          ./toolbox/create_config.sh

      - name: Fetch test data
        run: |
          git clone https://github.com/AstarVienna/METIS_Pipeline_Test_Data.git

      - uses: bissolli/gh-action-persist-workspace@v2
        with:
          action: persist
          artifactName: testEnv
