name: Setup edps cache

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  # schedule:
  #   # Run every day at 2:00 UTC
  #   - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: cache dependencies
        id: cache-dep
        uses: awalsh128/cache-apt-pkgs-action@latest
        env:
          cache-name: cache-dependencies
        with:
          packages: wget gcc  automake autogen libtool gsl-bin libgsl-dev libfftw3-bin libfftw3-dev fftw-dev
            curl bzip2 less subversion git cppcheck lcov valgrind
            zlib1g zlib1g-dev
            liberfa1 liberfa-dev
            libcurl4-openssl-dev libcurl4
            tmux ripgrep file
            libcfitsio-bin libcfitsio-dev
            wcslib-dev wcslib-tools
            libcpl-dev
            python3-astropy python3-matplotlib python3-numpy
            perl cmake
            graphviz meld
            python3-pip python3-full
            python3-jupyter-core python3-jupyter-client python3-notebook
            emacs vim nano
          version: 1.0

      # - if: ${{ steps.cache-dep.outputs.cache-hit != 'true' }}

      #   name: Install dependencies
      #   run: |
      #     sudo ./toolbox/install_dependencies_ubuntu.sh
      #     # python3 -m venv metispipe
      #     # . metispipe/bin/activate
      #     export PYCPL_RECIPE_DIR="$(pwd)/metisp/pyrecipes/"
      #     ./toolbox/install_edps.sh
      #     ./toolbox/create_config.sh

      - if: ${{ steps.cache-dep.outputs.cache-hit != 'true' }}

        name: Fetch test data
        run: |
          git clone https://github.com/AstarVienna/METIS_Pipeline_Test_Data.git
